# Generated by Django 5.0.6 on 2025-05-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='transaction_images/'),
        ),
    ]
