# Generated by Django 5.0.6 on 2025-05-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transaction_options_transaction_purchase_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='theme',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purchase_name',
            field=models.CharField(help_text="Name of the purchase (e.g., 'Coffee', 'Netflix')", max_length=200),
        ),
    ]
