# Generated by Django 5.0.6 on 2025-05-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_image_upload_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='purchase_reflection',
            field=models.CharField(blank=True, choices=[('happy', "I'm happy with this purchase"), ('regret', 'I regret this purchase'), ('undecided', 'I am undecided')], help_text='Do you regret this purchase?', max_length=10, null=True),
        ),
    ]
