# Generated by Django 5.0.6 on 2025-05-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_journalentry_options_journalentry_mood_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={},
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='image',
        ),
    ]
