# Generated by Django 5.0.6 on 2025-05-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_journalentry_options_remove_journalentry_mood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='transaction_images/'),
        ),
    ]
