# Generated by Django 5.0.6 on 2025-05-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='purchase_name',
            field=models.CharField(blank=True, help_text="Name of the purchase (e.g., 'Coffee', 'Netflix')", max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reflection',
            field=models.TextField(blank=True, help_text='Your thoughts and reflections about this purchase'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10),
        ),
    ]
