# Generated by Django 5.0.6 on 2025-05-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_transaction_is_active_transaction_is_recurring_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date', '-created_at'], 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AddField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(blank=True, choices=[('😊', 'Happy'), ('😌', 'Content'), ('😐', 'Neutral'), ('😔', 'Sad'), ('😡', 'Angry'), ('😰', 'Anxious'), ('🤔', 'Thoughtful'), ('🎯', 'Focused'), ('💪', 'Motivated'), ('😴', 'Tired')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=200),
        ),
    ]
